version: '3.8'
services:
  database:
    image: mysql:8.0.33
    container_name: web-crawler-database
    command:
      - --default-authentication-plugin=mysql_native_password
    env_file:
      - ./database/.env
    ports:
      - '3306:3306'
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping --host=localhost --user=root --password=password
      interval: 30s
      retries: 10
      start_period: 1m
      timeout: 30s
    networks:
      - backend
  backend-openapi:
    build: ./backend-openapi
    container_name: web-crawler-backend-openapi
    env_file:
      - ./backend-openapi/.env
    environment:
      - MYSQL_HOST=database
    ports:
      - '3001:3001'
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: curl -f http://localhost:3001/healthcheck
      interval: 15s
      retries: 10
      start_period: 15s
      timeout: 15s
    networks:
      - backend
  backend-graphql:
    build: ./backend-graphql
    container_name: web-crawler-backend-graphql
    env_file:
      - ./backend-graphql/.env
    environment:
      - MYSQL_HOST=database
    ports:
      - '3002:3002'
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: curl -f http://localhost:3002/healthcheck
      interval: 15s
      retries: 10
      start_period: 15s
      timeout: 15s
    networks:
      - backend
  frontend:
    build: ./frontend
    container_name: web-crawler-frontend
    env_file:
      - ./frontend/.env
    ports:
      - '3000:3000'
    depends_on:
      backend-openapi:
        condition: service_healthy
      backend-graphql:
        condition: service_healthy
networks:
  backend:
