version: '3.8'
services:
  database:
    image: mysql:8.0.33
    container_name: web-crawler-database
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysql --host=localhost --user=root --password=$${MYSQL_ROOT_PASSWORD} --execute='USE db;'
      interval: 15s
      retries: 10
      start_period: 2m
      timeout: 5s
    networks:
      - backend
  backend-openapi:
    build: ./backend-openapi
    container_name: web-crawler-backend-openapi
    env_file:
      - ./backend-openapi/.env
    environment:
      - MYSQL_HOST=database
    ports:
      - '3001:3001'
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3001/healthcheck']
      interval: 15s
      retries: 100
      start_period: 2m
      timeout: 10s
    networks:
      - backend
  backend-graphql:
    build: ./backend-graphql
    container_name: web-crawler-backend-graphql
    env_file:
      - ./backend-graphql/.env
    environment:
      - MYSQL_HOST=database
    ports:
      - '3002:3002'
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3002/healthcheck']
      interval: 15s
      retries: 100
      start_period: 2m
      timeout: 10s
    networks:
      - backend
  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_OPENAPI_PORT: 3001
        REACT_APP_GRAPHQL_PORT: 3002
        REACT_APP_BACKEND_ADDR: localhost
    container_name: web-crawler-frontend
    ports:
      - '3000:3000'
    depends_on:
      backend-openapi:
        condition: service_healthy
      backend-graphql:
        condition: service_healthy
networks:
  backend:
