version: '3.9'
services:
  database:
    image: mysql:8.0.33
    container_name: web-crawler-mysql
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
