openapi: '3.0.0'
info:
  title: web-crawler
  description: HTTP-based endpoint
  version: '1.0.0'
paths:
  /api/v1/records:
    get:
      operationId: getAllRecords
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecordFull'
        '5XX':
          description: 'Internal Server Error'
    post:
      operationId: createRecord
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecordBase'
      responses:
        '201':
          description: 'Created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecordId'
        '5XX':
          description: 'Internal Server Error'
  /api/v1/records/{recId}:
    put:
      operationId: updateRecord
      parameters:
        - name: recId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/EntityId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecordBase'
      responses:
        '204':
          description: 'Updated'
        '404':
          description: 'Not Found'
        '5XX':
          description: 'Unexpected Server Error'
    delete:
      operationId: deleteRecord
      parameters:
        - name: recId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/EntityId'
      responses:
        '204':
          description: 'Deleted'
        '404':
          description: 'Not Found'
        '5XX':
          description: 'Internal Server Error'
  /api/v1/executions:
    get:
      operationId: getAllExecutions
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExecutionFull'
        '5XX':
          description: 'Internal Server Error'
    post:
      operationId: createExecution
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecordId'
      responses:
        '204':
          description: 'Created'
        '404':
          description: 'Not Found'
        '5XX':
          description: 'Internal Server Error'
components:
  schemas:
    EntityId:
      type: integer
      format: int64
      minimum: 1
    EntityLabel:
      type: string
      description: 'User-defined label.'
      minLength: 1
      maxLength: 1024
      example: 'Example website'
    RecordId:
      type: object
      properties:
        recId:
          $ref: '#/components/schemas/EntityId'
      required:
        - recId
    RecordTag:
      type: string
      minLength: 1
      maxLength: 64
    RecordBase:
      type: object
      properties:
        url:
          type: string
          format: uri
          description: 'Entry point of crawling.'
          maxLength: 2048
          example: 'http://www.example.com/'
        regexp:
          type: string
          description: 'Boundary regular expression.'
          minLength: 1
          maxLength: 1024
          example: '*'
        period:
          type: integer
          format: int32
          minimum: 1
          description: 'Periodicity of crawling (in minutes).'
          example: 3
        label:
          $ref: '#/components/schemas/EntityLabel'
        active:
          type: boolean
          description: 'Active records are crawled based on the periodicity.'
          example: true
        tags:
          type: array
          description: 'User-defined tags / keywords.'
          items:
            $ref: '#/components/schemas/RecordTag'
          example: [ 'a', 'b', 'c' ]
      required:
        - url
        - regexp
        - period
        - label
        - active
        - tags
    ExecutionStatus:
      type: string
      enum:
        - 'CREATED'
        - 'PLANNED'
        - 'CRAWLING'
        - 'FAILURE'
        - 'SUCCESS'
    NullableExecutionTime:
      type: string
      format: date-time
      nullable: true
    RecordLastExec:
      type: object
      properties:
        lastExecStatus:
          $ref: '#/components/schemas/ExecutionStatus'
          description: 'Current status of the last execution.'
        lastExecCreateTime:
          $ref: '#/components/schemas/NullableExecutionTime'
          description: 'Create time of the last execution.'
        lastExecFinishTime:
          $ref: '#/components/schemas/NullableExecutionTime'
          description: 'End time of the last execution.'
      required:
        - lastExecStatus
        - lastExecEndTime
        - lastExecStartTime
    RecordFull:
      allOf:
        - $ref: '#/components/schemas/RecordId'
        - $ref: '#/components/schemas/RecordBase'
        - $ref: '#/components/schemas/RecordLastExec'
    ExecutionFull:
      type: object
      properties:
        recId:
          $ref: '#/components/schemas/EntityId'
        exeId:
          $ref: '#/components/schemas/EntityId'
        label:
          $ref: '#/components/schemas/EntityLabel'
        status:
          $ref: '#/components/schemas/ExecutionStatus'
        createTime:
          type: string
          format: date-time
          description: 'Time of creation.'
        finishTime:
          $ref: '#/components/schemas/NullableExecutionTime'
          description: 'Time of finished crawling.'
        nodCount:
          type: integer
          format: int32
          minimum: 0
      required:
        - recId
        - exeId
        - label
        - status
        - createTime
        - finishTime
        - nodCount
